package admin

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.84

import (
	"context"
	"volunteer-scheduler/graph/admin/generated"
)

// AssignVolunteerToShift is the resolver for the assignVolunteerToShift field.
func (r *mutationResolver) AssignVolunteerToShift(ctx context.Context, shiftID string, volunteerID string) (*generated.UpdateResult, error) {
	result, err := r.ShiftService.AssignVolunteerToShift(ctx, shiftID, volunteerID)
	if err != nil {
		return nil, err
	}
	return toGenUpdateResult(result), nil
}

// UpdateVolunteerProfile is the resolver for the updateVolunteerProfile field.
func (r *mutationResolver) UpdateVolunteerProfile(ctx context.Context, profile generated.UpdateVolunteerInput) (*generated.UpdateResult, error) {
	result, err := r.VolunteerService.UpdateVolunteerProfile(ctx, toModelUpdateVolunteerInput(&profile))
	if err != nil {
		return nil, err
	}
	return toGenUpdateResult(result), nil
}

// CancelShift is the resolver for the cancelShift field.
func (r *mutationResolver) CancelShift(ctx context.Context, shiftID string, volunteerID string) (*generated.UpdateResult, error) {
	result, err := r.ShiftService.CancelShiftAssignment(ctx, shiftID, volunteerID)
	if err != nil {
		return nil, err
	}
	return toGenUpdateResult(result), nil
}

// CreateVolunteer is the resolver for the createVolunteer field.
func (r *mutationResolver) CreateVolunteer(ctx context.Context, newVol generated.NewVolunteerInput) (*generated.InsertResult, error) {
	result, err := r.VolunteerService.CreateVolunteer(ctx, toModelNewVolunteerInput(&newVol))
	if err != nil {
		return nil, err
	}
	return toGenInsertResult(result), nil
}

// CreateEvent is the resolver for the createEvent field.
func (r *mutationResolver) CreateEvent(ctx context.Context, newEvent generated.NewEventInput) (*generated.InsertResult, error) {
	result, err := r.EventService.CreateEvent(ctx, toModelNewEventInput(&newEvent))
	if err != nil {
		return nil, err
	}
	return toGenInsertResult(result), nil
}

// Events is the resolver for the events field.
func (r *queryResolver) Events(ctx context.Context, filter *generated.EventFilterInput) ([]*generated.Event, error) {
	events, err := r.EventService.GetFilteredEvents(ctx, toModelEventFilterInput(filter))
	if err != nil {
		return nil, err
	}
	return toGenEvents(events), nil
}

// EventByID
// Returns the details for an event, including shifts.
func (r *queryResolver) EventByID(ctx context.Context, id string) (*generated.Event, error) {
	event, err := r.EventService.GetEventByID(ctx, id)
	if err != nil {
		return nil, err
	}
	return toGenEvent(event), nil
}

// AllVolunteers is the resolver for the allVolunteers field.
func (r *queryResolver) AllVolunteers(ctx context.Context, filter *generated.VolunteerFilterInput) ([]*generated.VolunteerProfile, error) {
	vols, err := r.VolunteerService.GetAllVolunteers(ctx, toModelVolunteerFilterInput(filter))
	if err != nil {
		return nil, err
	}
	return toGenVolunteerProfiles(vols), nil
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
