package admin

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.84

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"
	"volunteer-scheduler/graph/admin/generated"

	"github.com/lib/pq"
)

// CreateVolunteer is the resolver for the createVolunteer field.
func (r *mutationResolver) CreateVolunteer(ctx context.Context, firstName string, lastName string) (*generated.Volunteer, error) {
	query := `
		INSERT INTO volunteers (first_name, last_name, created_at)
		VALUES ($1, $2, NOW())
		RETURNING volunteer_id
	`

	var volunteerID int
	err := r.DB.QueryRowContext(ctx, query, firstName, lastName).Scan(&volunteerID)
	if err != nil {
		return nil, fmt.Errorf("error creating volunteer: %w", err)
	}

	return &generated.Volunteer{
		ID:        fmt.Sprintf("%d", volunteerID),
		FirstName: firstName,
		LastName:  lastName,
	}, nil
}

// AssignVolunteerToShift is the resolver for the assignVolunteerToShift field.
func (r *mutationResolver) AssignVolunteerToShift(ctx context.Context, shiftID string, volunteerID string) (*generated.AssignmentResult, error) {
	query := `
		INSERT INTO volunteer_shifts (volunteer_id, shift_id, assigned_at, status)
		VALUES ($1, $2, NOW(), 'confirmed')
		ON CONFLICT (volunteer_id, shift_id) DO NOTHING
	`

	_, err := r.DB.ExecContext(ctx, query, volunteerID, shiftID)
	if err != nil {
		return &generated.AssignmentResult{
			Success: false,
			Message: ptrString("Failed to assign volunteer to shift"),
		}, nil
	}

	return &generated.AssignmentResult{
		Success: true,
		Message: ptrString("Volunteer successfully assigned"),
	}, nil
}

// CreateEvent is the resolver for the createEvent field.
<<<<<<< HEAD:backend/graph/admin/schema.resolvers.go
func (r *mutationResolver) CreateEvent(ctx context.Context, name string, description *string, eventType generated.EventType, locationName *string) (*generated.Event, error) {
	panic(fmt.Errorf("not implemented: CreateEvent - createEvent"))
=======
func (r *mutationResolver) CreateEvent(ctx context.Context, name string, description *string, eventType model.EventType, locationName *string) (*model.Event, error) {
	return nil, fmt.Errorf("error creating event: not yet implemented")
	//panic(fmt.Errorf("not implemented: CreateEvent - createEvent"))
>>>>>>> main:vol_sched_api/graph/schema.resolvers.go
}

// Events is the resolver for the events field.
func (r *queryResolver) Events(ctx context.Context, filter *generated.EventFilter) ([]*generated.Event, error) {
	query := `
        SELECT DISTINCT
            e.event_id,
            e.event_name,
            e.description,
            e.event_is_virtual,
            e.location_id,
            l.location_name,
            l.street_address,
            l.city,
            l.state,
            l.zip_code
        FROM events e
        LEFT JOIN locations l ON e.location_id = l.location_id
        LEFT JOIN opportunities opp ON e.event_id = opp.event_id
        WHERE 1=1
    `

	args := []interface{}{}
	argCount := 1

	rows, err := r.DB.QueryContext(ctx, query, args...)
	if err != nil {
		return nil, fmt.Errorf("error querying events: %w", err)
	}
	defer rows.Close()

	// Now we have selected all of the events 
	eventsMap := make(map[string]*generated.Event)

	for rows.Next() {
		var e generated.Event
		var loc generated.Location
		var locationID *int
		var locationName, address, city, state, zipCode *string

		var eventInt int
		var eventStr string
		var isVirtual bool // Temporary variable for database value

		err := rows.Scan(
			&eventInt,
			&e.Name,
			&e.Description,
			&isVirtual,
			&locationID,
			&locationName,
			&address,
			&city,
			&state,
			&zipCode,
		)
		if err != nil {
			return nil, fmt.Errorf("error scanning event: %w", err)
		}

		eventStr = fmt.Sprintf("%d", eventInt) // string for GraphQL.
		e.ID = eventStr

		// Determine if event is virtual, in person, or both.
		if isVirtual && locationID != nil {
			e.EventType = "HYBRID"
		} else if isVirtual {
			e.EventType = "VIRTUAL"
		} else {
			e.EventType = "IN_PERSON"
		}

		// Check if we've already processed this event.
		if _, exists := eventsMap[eventStr]; !exists {
			// Add location if it exists.
			if locationID != nil && address != nil && city != nil && state != nil {
				loc.Name = locationName
				loc.Address = *address
				loc.City = *city
				loc.State = *state
				loc.ZipCode = zipCode
				e.Location = &loc
			}

			eventsMap[eventStr] = &e
		}
	}

	// Now fetch shifts for these events.
	if len(eventsMap) > 0 {
		eventIDs := []string{}
		for id := range eventsMap {
			eventIDs = append(eventIDs, id)
		}

		shiftsQuery := `
            SELECT 
                s.shift_id,
                s.shift_start,
                s.shift_end,
                opp.role,
                opp.event_id
            FROM shifts s
            JOIN opportunities opp ON s.opportunity_id = opp.opportunity_id
            WHERE opp.event_id = ANY($1)
        `

		shiftArgs := []interface{}{pq.Array(eventIDs)}
		argNum := 2

		shiftRows, err := r.DB.QueryContext(ctx, shiftsQuery, shiftArgs...)
		if err != nil {
			return nil, fmt.Errorf("error querying shifts: %w", err)
		}
		defer shiftRows.Close()

		// Do some formatting.
		for shiftRows.Next() {
			var shift generated.Shift
			var eventInt int
			var eventStr string
			var startTime, endTime time.Time
			var role string
			var shiftInt int

			err := shiftRows.Scan(
				&shiftInt,
				&startTime,
				&endTime,
				&role,
				&eventInt,
			)
			if err != nil {
				return nil, fmt.Errorf("error scanning shift: %w", err)
			}

			eventStr = fmt.Sprintf("%d", eventInt) // string for GraphQL.

			// Format the timestamps.
			shift.Date = startTime.Format("2006-01-02")
			shift.StartTime = startTime.Format("15:04:05")
			shift.EndTime = endTime.Format("15:04:05")

			// Convert role string to RoleType enum.
			shift.Role = generated.RoleType(strings.ToUpper(role))

			if event, exists := eventsMap[eventStr]; exists {
				event.Shifts = append(event.Shifts, &shift)
			}
		}
	}

	// Convert map to slice
	events := make([]*generated.Event, 0, len(eventsMap))
	for _, event := range eventsMap {
		events = append(events, event)
	}

	return events, nil
}

// Event is the resolver for the event field.
func (r *queryResolver) Event(ctx context.Context, id string) (*generated.Event, error) {
	query := `
		SELECT 
			e.event_id,
			e.event_name,
			e.description,
			e.event_is_virtual,
			e.location_id,
			l.location_name,
			l.street_address,
			l.city,
			l.state,
			l.zip_code
		FROM events e
		LEFT JOIN locations l ON e.location_id = l.location_id
		WHERE e.event_id = $1
	`
	var event generated.Event
	var eventID int
	var isVirtual bool
	var locationID *int
	var locationName, address, city, state, zipCode *string

	err := r.DB.QueryRowContext(ctx, query, id).Scan(
		&eventID,
		&event.Name,
		&event.Description,
		&isVirtual,
		&locationID,
		&locationName,
		&address,
		&city,
		&state,
		&zipCode,
	)

	if err == sql.ErrNoRows {
		return nil, fmt.Errorf("event not found")
	}
	if err != nil {
		return nil, fmt.Errorf("error querying event: %w", err)
	}

	event.ID = fmt.Sprintf("%d", eventID) // string for GraphQl

	// Determine if the event is virtual, in person, or either (hybrid).
	if isVirtual && locationID != nil {
		event.EventType = "HYBRID"
	} else if isVirtual {
		event.EventType = "VIRTUAL"
	} else {
		event.EventType = "IN_PERSON"
	}

	// Add location if it exists.
	if locationID != nil && address != nil && city != nil && state != nil {
		loc := &generated.Location{
			Name:    locationName,
			Address: *address,
			City:    *city,
			State:   *state,
			ZipCode: zipCode,
		}
		event.Location = loc
	}

	// Fetch opportunities for this event
	opportunities, err := r.getOpportunitiesForEvent(ctx, eventID)
	if err != nil {
		return nil, err
	}
	event.Opportunities = opportunities

	return &event, nil
}

// Volunteers is the resolver for the volunteers field.
func (r *queryResolver) Volunteers(ctx context.Context, qualifications []string) ([]*generated.Volunteer, error) {
	var query string
	var args []interface{}

	if len(qualifications) > 0 {
		// Filter by qualifications
		query = `
			SELECT DISTINCT v.volunteer_id, v.first_name, v.last_name
			FROM volunteers v
			JOIN volunteer_qualifications vq ON v.volunteer_id = vq.volunteer_id
			WHERE vq.qualification = ANY($1)
		`
		args = append(args, pq.Array(qualifications))
	} else {
		// Get all volunteers
		query = `
			SELECT volunteer_id, first_name, last_name
			FROM volunteers
		`
	}

	rows, err := r.DB.QueryContext(ctx, query, args...)
	if err != nil {
		return nil, fmt.Errorf("error querying volunteers: %w", err)
	}
	defer rows.Close()

	var volunteers []*generated.Volunteer
	for rows.Next() {
		var v generated.Volunteer
		var volunteerID int

		err := rows.Scan(&volunteerID, &v.FirstName, &v.LastName)
		if err != nil {
			return nil, fmt.Errorf("error scanning volunteer: %w", err)
		}

		v.ID = fmt.Sprintf("%d", volunteerID)
		volunteers = append(volunteers, &v)
	}

	return volunteers, nil
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
