package admin

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.84

import (
	"context"
	"fmt"
	"strconv"
	"volunteer-scheduler/graph/admin/generated"
	"volunteer-scheduler/middleware"
)

// CreateFundingEntity is the resolver for the createFundingEntity field.
func (r *mutationResolver) CreateFundingEntity(ctx context.Context, input generated.NewFundingEntityInput) (*generated.MutationResult, error) {
	m := toModelNewFundingEntityInput(input)
	id, err := r.FundingEntityService.CreateFundingEntity(ctx, m.Name, m.Description)
	if err != nil {
		return nil, err
	}
	idStr := strconv.Itoa(id)
	return &generated.MutationResult{Success: true, ID: &idStr}, nil
}

// CreateJobType is the resolver for the createJobType field.
func (r *mutationResolver) CreateJobType(ctx context.Context, newJob generated.NewJobTypeInput) (*generated.MutationResult, error) {
	result, err := r.ShiftService.CreateJobType(ctx, toModelNewJobTypeInput(newJob))
	if err != nil {
		return nil, err
	}
	return toGenMutationResult(result), nil
}

// DeleteFundingEntity is the resolver for the deleteFundingEntity field.
func (r *mutationResolver) DeleteFundingEntity(ctx context.Context, id int) (*generated.MutationResult, error) {
	err := r.FundingEntityService.DeleteFundingEntity(ctx, id)
	if err != nil {
		return nil, err
	}
	return &generated.MutationResult{Success: true}, nil
}

// DeleteJobType is the resolver for the deleteJobType field.
func (r *mutationResolver) DeleteJobType(ctx context.Context, jobID int) (*generated.MutationResult, error) {
	result, err := r.ShiftService.DeleteJobType(ctx, jobID)
	if err != nil {
		return nil, err
	}
	return toGenMutationResult(result), nil
}

// UpdateFundingEntity is the resolver for the updateFundingEntity field.
func (r *mutationResolver) UpdateFundingEntity(ctx context.Context, input generated.UpdateFundingEntityInput) (*generated.MutationResult, error) {
	m := toModelUpdateFundingEntityInput(input)
	err := r.FundingEntityService.UpdateFundingEntity(ctx, m.ID, m.Name, m.Description)
	if err != nil {
		return nil, err
	}
	return &generated.MutationResult{Success: true}, nil
}

// UpdateJobType is the resolver for the updateJobType field.
func (r *mutationResolver) UpdateJobType(ctx context.Context, job generated.UpdateJobTypeInput) (*generated.MutationResult, error) {
	result, err := r.ShiftService.UpdateJobType(ctx, toModelUpdateJobTypeInput(job))
	if err != nil {
		return nil, err
	}
	return toGenMutationResult(result), nil
}

// CreateEvent is the resolver for the createEvent field.
func (r *mutationResolver) CreateEvent(ctx context.Context, newEvent generated.NewEventInput) (*generated.MutationResult, error) {
	result, err := r.EventService.CreateEvent(ctx, toModelNewEventInput(newEvent))
	if err != nil {
		return nil, err
	}
	return toGenMutationResult(result), nil
}

// CreateEventDate is the resolver for the createEventDate field.
func (r *mutationResolver) CreateEventDate(ctx context.Context, newDate generated.AddEventDateInput) (*generated.MutationResult, error) {
	result, err := r.EventService.CreateEventDate(ctx, toModelAddEventDate(newDate))
	if err != nil {
		return nil, err
	}
	return toGenMutationResult(result), nil
}

// CreateOpportunity is the resolver for the createOpportunity field.
func (r *mutationResolver) CreateOpportunity(ctx context.Context, newOpp generated.NewOpportunityInput) (*generated.MutationResult, error) {
	result, err := r.ShiftService.CreateOpportunity(ctx, toModelNewOpportunity(newOpp))
	if err != nil {
		return nil, err
	}
	return toGenMutationResult(result), nil
}

// CreateShift is the resolver for the createShift field.
func (r *mutationResolver) CreateShift(ctx context.Context, newShift generated.AddShiftInput) (*generated.MutationResult, error) {
	result, err := r.ShiftService.CreateShift(ctx, toModelAddShiftInput(newShift))
	if err != nil {
		return nil, err
	}
	return toGenMutationResult(result), nil
}

// DeleteEvent is the resolver for the deleteEvent field.
func (r *mutationResolver) DeleteEvent(ctx context.Context, eventID string, scope *generated.RecurrenceUpdateScope) (*generated.MutationResult, error) {
	result, err := r.EventService.DeleteEvent(ctx, eventID, toModelScope(scope))
	if err != nil {
		return nil, err
	}
	return toGenMutationResult(result), nil
}

// DeleteEventDate is the resolver for the deleteEventDate field.
func (r *mutationResolver) DeleteEventDate(ctx context.Context, eventDateID string) (*generated.MutationResult, error) {
	result, err := r.EventService.DeleteEventDate(ctx, eventDateID)
	if err != nil {
		return nil, err
	}
	return toGenMutationResult(result), nil
}

// DeleteOpportunity is the resolver for the deleteOpportunity field.
func (r *mutationResolver) DeleteOpportunity(ctx context.Context, oppID string) (*generated.MutationResult, error) {
	result, err := r.ShiftService.DeleteOpportunity(ctx, oppID)
	if err != nil {
		return nil, err
	}
	return toGenMutationResult(result), nil
}

// DeleteShift is the resolver for the deleteShift field.
func (r *mutationResolver) DeleteShift(ctx context.Context, shiftID string) (*generated.MutationResult, error) {
	result, err := r.ShiftService.DeleteShift(ctx, shiftID)
	if err != nil {
		return nil, err
	}
	return toGenMutationResult(result), nil
}

// UpdateEvent is the resolver for the updateEvent field.
func (r *mutationResolver) UpdateEvent(ctx context.Context, event generated.UpdateEventInput) (*generated.MutationResult, error) {
	result, err := r.EventService.UpdateEvent(ctx, toModelUpdateEventInput(event))
	if err != nil {
		return nil, err
	}
	return toGenMutationResult(result), nil
}

// UpdateEventDate is the resolver for the updateEventDate field.
func (r *mutationResolver) UpdateEventDate(ctx context.Context, date generated.UpdateEventDateInput) (*generated.MutationResult, error) {
	result, err := r.EventService.UpdateEventDate(ctx, toModelUpdateEventDateInput(date))
	if err != nil {
		return nil, err
	}
	return toGenMutationResult(result), nil
}

// UpdateOpportunity is the resolver for the updateOpportunity field.
func (r *mutationResolver) UpdateOpportunity(ctx context.Context, opp generated.UpdateOpportunityInput) (*generated.MutationResult, error) {
	result, err := r.ShiftService.UpdateOpportunity(ctx, toModelUpdateOpportunity(opp))
	if err != nil {
		return nil, err
	}
	return toGenMutationResult(result), nil
}

// UpdateShift is the resolver for the updateShift field.
func (r *mutationResolver) UpdateShift(ctx context.Context, shift generated.UpdateShiftInput) (*generated.MutationResult, error) {
	result, err := r.ShiftService.UpdateShift(ctx, toModelUpdateShift(shift))
	if err != nil {
		return nil, err
	}
	return toGenMutationResult(result), nil
}

// UpdateFeedbackStatus is the resolver for the updateFeedbackStatus field.
func (r *mutationResolver) UpdateFeedbackStatus(ctx context.Context, su generated.FeedbackStatusUpdateInput) (*generated.MutationResult, error) {
	volId, ok := middleware.VolunteerIdFromContext(ctx)
	if !ok {
		return nil, fmt.Errorf("unauthorized")
	}

	result, err := r.FeedbackService.UpdateFeedbackStatus(ctx, volId, toModelFeedbackStatusUpdateInput(su))
	if err != nil {
		return nil, err
	}

	return toGenMutationResult(result), nil
}

// AddFeedbackNote is the resolver for the addFeedbackNote field.
func (r *mutationResolver) AddFeedbackNote(ctx context.Context, note generated.FeedbackNoteInput) (*generated.MutationResult, error) {
	adminId, ok := middleware.VolunteerIdFromContext(ctx)
	if !ok {
		return nil, fmt.Errorf("unauthorized")
	}

	result, err := r.FeedbackService.AddFeedbackNote(ctx, adminId, toModelFeedbackNoteInput(note))
	if err != nil {
		return nil, err
	}
	return toGenMutationResult(result), nil
}

// EmailFeedbackSubmitter is the resolver for the emailFeedbackSubmitter field.
func (r *mutationResolver) EmailFeedbackSubmitter(ctx context.Context, input generated.FeedbackEmailInput) (*generated.MutationResult, error) {
	volId, ok := middleware.VolunteerIdFromContext(ctx)
	if !ok {
		return nil, fmt.Errorf("unauthorized")
	}

	result, err := r.FeedbackService.EmailFeedbackSubmitter(ctx, volId, toModelFeedbackEmailInput(input))
	if err != nil {
		return nil, err
	}

	return toGenMutationResult(result), nil
}

// CreateStaff is the resolver for the createStaff field.
func (r *mutationResolver) CreateStaff(ctx context.Context, newStaff generated.NewStaffInput) (*generated.MutationResult, error) {
	result, err := r.StaffService.CreateStaff(ctx, toModelNewStaffInput(newStaff))
	if err != nil {
		return nil, err
	}
	return toGenMutationResult(result), nil
}

// DeleteStaff is the resolver for the deleteStaff field.
func (r *mutationResolver) DeleteStaff(ctx context.Context, staffID string) (*generated.MutationResult, error) {
	result, err := r.StaffService.DeleteStaff(ctx, staffID)
	if err != nil {
		return nil, err
	}
	return toGenMutationResult(result), nil
}

// UpdateStaff is the resolver for the updateStaff field.
func (r *mutationResolver) UpdateStaff(ctx context.Context, staff generated.UpdateStaffInput) (*generated.MutationResult, error) {
	result, err := r.StaffService.UpdateStaff(ctx, toModelUpdateStaffInput(staff))
	if err != nil {
		return nil, err
	}
	return toGenMutationResult(result), nil
}

// CreateVenue is the resolver for the createVenue field.
func (r *mutationResolver) CreateVenue(ctx context.Context, newVenue generated.NewVenueInput) (*generated.MutationResult, error) {
	result, err := r.VenueService.CreateVenue(ctx, toModelNewVenueInput(newVenue))
	if err != nil {
		return nil, err
	}
	return toGenMutationResult(result), nil
}

// DeleteVenue is the resolver for the deleteVenue field.
func (r *mutationResolver) DeleteVenue(ctx context.Context, venueID string) (*generated.MutationResult, error) {
	result, err := r.VenueService.DeleteVenue(ctx, venueID)
	if err != nil {
		return nil, err
	}
	return toGenMutationResult(result), nil
}

// UpdateVenue is the resolver for the updateVenue field.
func (r *mutationResolver) UpdateVenue(ctx context.Context, venue generated.UpdateVenueInput) (*generated.MutationResult, error) {
	result, err := r.VenueService.UpdateVenue(ctx, toModelUpdateVenue(venue))
	if err != nil {
		return nil, err
	}
	return toGenMutationResult(result), nil
}

// CreateVolunteer is the resolver for the createVolunteer field.
func (r *mutationResolver) CreateVolunteer(ctx context.Context, newVol generated.NewVolunteerInput) (*generated.MutationResult, error) {
	creatorId, ok := middleware.VolunteerIdFromContext(ctx)
	if !ok {
		return nil, fmt.Errorf("unauthorized")
	}

	result, err := r.VolunteerService.CreateVolunteer(ctx, creatorId, toModelNewVolunteerInput(newVol))
	if err != nil {
		return nil, err
	}
	return toGenMutationResult(result), nil
}

// DeleteVolunteer is the resolver for the deleteVolunteer field.
func (r *mutationResolver) DeleteVolunteer(ctx context.Context, volunteerID string) (*generated.MutationResult, error) {
	result, err := r.VolunteerService.DeleteVolunteer(ctx, volunteerID)
	if err != nil {
		return nil, err
	}
	return toGenMutationResult(result), nil
}

// UpdateVolunteer is the resolver for the updateVolunteer field.
func (r *mutationResolver) UpdateVolunteer(ctx context.Context, profile generated.UpdateVolunteerInput) (*generated.MutationResult, error) {
	result, err := r.VolunteerService.UpdateVolunteerProfile(ctx, toModelUpdateVolunteerInput(profile))
	if err != nil {
		return nil, err
	}
	return toGenMutationResult(result), nil
}

// AssignVolunteerToShift is the resolver for the assignVolunteerToShift field.
func (r *mutationResolver) AssignVolunteerToShift(ctx context.Context, shiftID string, volunteerID string) (*generated.MutationResult, error) {
	result, err := r.ShiftService.AssignVolunteerToShift(ctx, shiftID, volunteerID)
	if err != nil {
		return nil, err
	}
	return toGenMutationResult(result), nil
}

// CancelShift is the resolver for the cancelShift field.
func (r *mutationResolver) CancelShift(ctx context.Context, shiftID string, volunteerID string) (*generated.MutationResult, error) {
	result, err := r.ShiftService.CancelShiftAssignment(ctx, shiftID, volunteerID)
	if err != nil {
		return nil, err
	}
	return toGenMutationResult(result), nil
}

// Events is the resolver for the filteredEvents field.
func (r *queryResolver) Events(ctx context.Context, filter *generated.EventFilterInput) ([]*generated.Event, error) {
	events, err := r.EventService.FetchEvents(ctx, toModelEventFilterInput(filter))
	if err != nil {
		return nil, err
	}
	return toGenEvents(events), nil
}

// Event is the resolver for the EventById field.
func (r *queryResolver) Event(ctx context.Context, eventID string) (*generated.Event, error) {
	e, err := r.EventService.FetchEvent(ctx, eventID)
	if err != nil {
		return nil, err
	}
	return toGenEvent(e), nil
}

// FundingEntities is the resolver for the fundingEntities field.
func (r *queryResolver) FundingEntities(ctx context.Context) ([]*generated.FundingEntity, error) {
	fes, err := r.EventService.FetchFundingEntities(ctx)
	if err != nil {
		return nil, err
	}
	return toGenFundingEntities(fes), nil
}

// OpportunitiesForEvent is the resolver for the opportunitiesForEvent field.
func (r *queryResolver) OpportunitiesForEvent(ctx context.Context, eventID string) ([]*generated.Opportunity, error) {
	opps, err := r.ShiftService.FetchOpportunitiesForEvent(ctx, eventID)
	if err != nil {
		return nil, err
	}
	return toGenOpportunities(opps), nil
}

// Feedback is the resolver for the feedback field.
func (r *queryResolver) Feedback(ctx context.Context, filter *generated.FeedbackFilterInput) ([]*generated.Feedback, error) {
	fbs, err := r.FeedbackService.FetchFeedback(ctx, toModelFeedbackFilterInput(filter))
	if err != nil {
		return nil, err
	}
	return toGenFeedbacks(fbs), nil
}

// FeedbackDetail is the resolver for the feedbackDetail field.
func (r *queryResolver) FeedbackDetail(ctx context.Context, feedbackID string) (*generated.Feedback, error) {
	fb, err := r.FeedbackService.FetchFeedbackDetail(ctx, feedbackID)
	if err != nil {
		return nil, err
	}
	return toGenFeedback(fb), nil
}

// Attachment is the resolver for the attachment field.
func (r *queryResolver) FeedbackAttachment(ctx context.Context, attachmentID int) (*generated.FeedbackAttachment, error) {
	att, err := r.FeedbackService.FetchAttachment(ctx, attachmentID)
	if err != nil {
		return nil, err
	}
	return toGenFeedbackAttachment(att), nil
}

// Staff is the resolver for the staff field.
func (r *queryResolver) Staff(ctx context.Context) ([]*generated.Staff, error) {
	allStaff, err := r.StaffService.FetchAllStaff(ctx)
	if err != nil {
		return nil, err
	}
	return toGenAllStaff(allStaff), nil
}

// Venues is the resolver for the venues field.
func (r *queryResolver) Venues(ctx context.Context) ([]*generated.Venue, error) {
	venues, err := r.VenueService.FetchVenues(ctx)
	if err != nil {
		return nil, err
	}
	return toGenVenues(venues), nil
}

// AllVolunteers is the resolver for the allVolunteers field.
func (r *queryResolver) Volunteers(ctx context.Context, filter *generated.VolunteerFilterInput) ([]*generated.Volunteer, error) {
	vols, err := r.VolunteerService.FetchVolunteers(ctx, toModelVolunteeFilterInput(filter))
	if err != nil {
		return nil, err
	}
	return toGenVolunteers(vols), nil
}

// Volunteer is the resolver for the volunteer field.
func (r *queryResolver) Volunteer(ctx context.Context, volID int) (*generated.Volunteer, error) {
	vol, err := r.VolunteerService.FetchVolunteer(ctx, volID)
	if err != nil {
		return nil, err
	}
	return toGenVolunteer(vol), nil
}

// VolunteerShifts is the resolver for the volunteerShifts field.
func (r *queryResolver) VolunteerShifts(ctx context.Context, volunteerID string, filter generated.ShiftTimeFilter) ([]*generated.VolunteerShift, error) {
	shifts, err := r.VolunteerService.FetchVolunteerShifts(ctx, volunteerID, toModelShiftTimeFilter(filter))
	if err != nil {
		return nil, err
	}
	return toGenVolunteerShifts(shifts), nil
}
