package admin

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.84

import (
	"context"
	"fmt"
	"volunteer-scheduler/graph/admin/generated"

	"github.com/99designs/gqlgen/graphql"
)

// AttachFileToFeedback is the resolver for the attachFileToFeedback field.
func (r *mutationResolver) AttachFileToFeedback(ctx context.Context, feedbackID string, file graphql.Upload) (*generated.MutationResult, error) {
	panic(fmt.Errorf("not implemented: AttachFileToFeedback - attachFileToFeedback"))
}

// GiveFeedback is the resolver for the giveFeedback field.
func (r *mutationResolver) GiveFeedback(ctx context.Context, feedback generated.NewFeedbackInput) (*generated.MutationResult, error) {
	panic(fmt.Errorf("not implemented: GiveFeedback - giveFeedback"))
}

// LookupValues is the resolver for the lookupValues field.
func (r *queryResolver) LookupValues(ctx context.Context) (*generated.LookupValues, error) {
	lookup, err := r.EventService.FetchLookups(ctx)
	if err != nil {
		return nil, err
	}
	genLookup := toGenLookupValues(*lookup)
	return &genLookup, nil
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
