package auth

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.84

import (
	"context"
	"fmt"
	"volunteer-scheduler/graph/auth/generated"
)

// RequestMagicLink is the resolver for the requestMagicLink field.
func (r *mutationResolver) RequestMagicLink(ctx context.Context, email string) (*generated.MagicLinkResult, error) {
	// IP and user agent not available at GraphQL layer without middleware,
	// so pass empty strings for now.
	token, err := r.MagicLinkService.GenerateMagicLink(ctx, email, "", "")
	if err != nil {
		err = fmt.Errorf("error generating magic link: %w", err)
		return &generated.MagicLinkResult{
			Success: false,
			Message: err.Error(),
			Email:   &email,
		}, nil
	}

	if err := r.MagicLinkService.SendMagicLinkEmail(ctx, email, token); err != nil {
		err = fmt.Errorf("error sending magic ling: %w", err)
		return &generated.MagicLinkResult{
			Success: false,
			Message: "Failed to send magic link email.",
			Email:   &email,
		}, nil
	}

	return &generated.MagicLinkResult{
		Success: true,
		Message: "Magic link sent! Check your email.",
		Email:   &email,
	}, nil
}

func (r *mutationResolver) ConsumeMagicLink(ctx context.Context, token string) (*generated.AuthResult, error) {
	email, err := r.MagicLinkService.ConsumeMagicLink(ctx, token)
	if err != nil {
		err = fmt.Errorf("error consuming magic link: %w", err)
		return &generated.AuthResult{
			Success: false,
			Message: err.Error(),
		}, nil
	}

	sessionToken, err := r.MagicLinkService.CreateSessionToken(ctx, email)
	if err != nil {
		err = fmt.Errorf("error creating session token: %w", err)
		return &generated.AuthResult{
			Success: false,
			Message: "Failed to create session.",
			Email:   &email,
		}, nil
	}

	return &generated.AuthResult{
		Success:      true,
		Message:      "Successfully authenticated.",
		Email:        &email,
		SessionToken: &sessionToken,
	}, nil
}

// AuthHealthCheck is the resolver for the _authHealthCheck field.
func (r *queryResolver) AuthHealthCheck(ctx context.Context) (*bool, error) {
	panic(fmt.Errorf("not implemented: AuthHealthCheck - _authHealthCheck"))
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
