package auth

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.84

import (
	"context"
	"fmt"
	"log"
	"net/http"
	"time"
	"volunteer-scheduler/graph/auth/generated"
	"volunteer-scheduler/middleware"
)

// RequestMagicLink is the resolver for the requestMagicLink field.
func (r *mutationResolver) RequestMagicLink(ctx context.Context, email string) (*generated.MagicLinkResult, error) {
	// IP and user agent not available at GraphQL layer without middleware,
	// so pass empty strings for now.
	token, err := r.MagicLinkService.GenerateMagicLink(ctx, email, "", "")
	if err != nil {
		err = fmt.Errorf("error generating magic link: %w", err)
		return &generated.MagicLinkResult{
			Success: false,
			Message: err.Error(),
			Email:   &email,
		}, nil
	}

	if err := r.MagicLinkService.SendMagicLinkEmail(ctx, email, token); err != nil {
		err = fmt.Errorf("error sending magic link: %w", err)
		log.Printf("[auth] %v", err)
		return &generated.MagicLinkResult{
			Success: false,
			Message: err.Error(),
			Email:   &email,
		}, nil
	}

	return &generated.MagicLinkResult{
		Success: true,
		Message: "Magic link sent! Check your email.",
		Email:   &email,
	}, nil
}

// ConsumeMagicLink is the resolver for the consumeMagicLink field.
// On success it sets an HttpOnly session cookie instead of returning the token.
func (r *mutationResolver) ConsumeMagicLink(ctx context.Context, token string) (*generated.AuthResult, error) {
	email, err := r.MagicLinkService.ConsumeMagicLink(ctx, token)
	if err != nil {
		err = fmt.Errorf("error consuming magic link: %w", err)
		return &generated.AuthResult{
			Success: false,
			Message: err.Error(),
		}, nil
	}

	sessionToken, expiresAt, err := r.MagicLinkService.CreateSessionToken(ctx, email)
	if err != nil {
		err = fmt.Errorf("error creating session token: %w", err)
		return &generated.AuthResult{
			Success: false,
			Message: "Failed to create session.",
			Email:   &email,
		}, nil
	}

	// Write the session token as an HttpOnly cookie so JavaScript cannot read it.
	// The cookie expiry matches the DB session exactly (both driven by SESSION_MAX_AGE).
	if w, ok := middleware.ResponseWriterFromContext(ctx); ok {
		cookie := &http.Cookie{
			Name:     "session",
			Value:    sessionToken,
			Path:     "/",
			HttpOnly: true,
			Secure:   r.IsProd, // HTTPS only in production
			SameSite: http.SameSiteLaxMode,
			Expires:  expiresAt,
		}
		if r.IsProd {
			// Frontend and backend are on different Railway domains, so cross-origin.
			cookie.SameSite = http.SameSiteNoneMode
		}
		http.SetCookie(w, cookie)
	}

	return &generated.AuthResult{
		Success: true,
		Message: "Successfully authenticated.",
		Email:   &email,
	}, nil
}

// RequestAccount is the resolver for the requestAccount field.
// No DB record is created — the request is emailed to all admins for review.
func (r *mutationResolver) RequestAccount(ctx context.Context, email string, firstName string, lastName string) (*generated.RequestResult, error) {
	if err := r.MagicLinkService.RequestAccount(ctx, email, firstName, lastName); err != nil {
		return &generated.RequestResult{
			Success: false,
			Message: "Failed to submit account request. Please try again later.",
		}, nil
	}

	return &generated.RequestResult{
		Success: true,
		Message: "Your request has been submitted. An administrator will be in touch soon.",
	}, nil
}

// Logout is the resolver for the logout field.
// Reads the session token from the HttpOnly cookie, invalidates it on the server,
// and clears the cookie.
func (r *mutationResolver) Logout(ctx context.Context) (*generated.LogoutResult, error) {
	// Read token from the session cookie.
	var token string
	if req, ok := middleware.RequestFromContext(ctx); ok {
		if cookie, err := req.Cookie("session"); err == nil {
			token = cookie.Value
		}
	}

	// Invalidate on the server (best-effort — clear the cookie regardless).
	if token != "" {
		if err := r.MagicLinkService.Logout(ctx, token); err != nil {
			log.Printf("[auth] logout server error: %v", err)
		}
	}

	// Clear the cookie by setting it expired.
	if w, ok := middleware.ResponseWriterFromContext(ctx); ok {
		http.SetCookie(w, &http.Cookie{
			Name:     "session",
			Value:    "",
			Path:     "/",
			HttpOnly: true,
			Secure:   r.IsProd,
			SameSite: http.SameSiteLaxMode,
			Expires:  time.Unix(0, 0),
			MaxAge:   -1,
		})
	}

	return &generated.LogoutResult{Success: true}, nil
}

// AuthHealthCheck is the resolver for the _authHealthCheck field.
func (r *queryResolver) AuthHealthCheck(ctx context.Context) (*bool, error) {
	panic(fmt.Errorf("not implemented: AuthHealthCheck - _authHealthCheck"))
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
