-- Add recurrence support and timezone to events.
--
-- recurrence_group_id  links all occurrences of the same recurring event.
--                      NULL means the event is a standalone (non-recurring) event.
--                      Generated by the application when a recurring event is created.
--
-- recurrence_order     1-based position within the series (1 = first occurrence).
--                      NULL for standalone events.
--
-- timezone             IANA timezone name used for recurrence arithmetic and display.
--                      Moved here from venues so virtual events can carry their own
--                      timezone. Defaults to America/Los_Angeles for existing rows.

ALTER TABLE events
    ADD COLUMN recurrence_group_id UUID         NULL,
    ADD COLUMN recurrence_order    INTEGER      NULL,
    ADD COLUMN timezone            TEXT         NOT NULL DEFAULT 'America/Los_Angeles';

CREATE INDEX idx_events_recurrence_group ON events(recurrence_group_id)
    WHERE recurrence_group_id IS NOT NULL;
