ALTER TYPE feedback_note_type RENAME VALUE 'VOLUNTEER_NOTE' TO 'VOLUNTEER_REPLY';
ALTER TYPE feedback_status RENAME VALUE 'RESOLVED_IMPLEMENTED' TO 'RESOLVED_GITHUB';

ALTER TABLE feedback ADD COLUMN IF NOT EXISTS github_issue_url TEXT;
