package volunteer

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.84

import (
	"context"
	"fmt"
	"io"
	"strconv"
	"volunteer-scheduler/graph/volunteer/generated"
	"volunteer-scheduler/middleware"

	"github.com/99designs/gqlgen/graphql"
)

// UpdateOwnProfile is the resolver for the updateOwnProfile field.
func (r *mutationResolver) UpdateOwnProfile(ctx context.Context, profile generated.UpdateOwnProfileInput) (*generated.VolunteerMutationResult, error) {
	volId, ok := middleware.VolunteerIdFromContext(ctx)
	if !ok {
		return nil, fmt.Errorf("unauthorized")
	}

	modProf := toModelUpdateOwnProfileInput(&profile)
	result, err := r.VolunteerService.UpdateOwnProfile(ctx, volId, *modProf)
	if err != nil {
		return nil, err
	}

	return toGenVolunteerMutationResult(result), nil
}

// AssignSelfToShift is the resolver for the assignSelfToShift field.
func (r *mutationResolver) AssignSelfToShift(ctx context.Context, shiftID string) (*generated.MutationResult, error) {
	volId, ok := middleware.VolunteerIdFromContext(ctx)
	if !ok {
		return nil, fmt.Errorf("unauthorized")
	}

	result, err := r.ShiftService.AssignSelfToShift(ctx, shiftID, volId)
	if err != nil {
		return nil, err
	}

	return toGenMutationResult(result), nil
}

// CancelOwnShift is the resolver for the cancelOwnShift field.
func (r *mutationResolver) CancelOwnShift(ctx context.Context, shiftID string) (*generated.MutationResult, error) {
	volId, ok := middleware.VolunteerIdFromContext(ctx)
	if !ok {
		return nil, fmt.Errorf("unauthorized")
	}

	result, err := r.ShiftService.CancelOwnShift(ctx, shiftID, volId)
	if err != nil {
		return nil, err
	}

	return toGenMutationResult(result), nil
}

// GiveFeedback is the resolver for the giveFeedback field.
func (r *mutationResolver) GiveFeedback(ctx context.Context, feedback generated.NewFeedbackInput) (*generated.MutationResult, error) {
	volId, ok := middleware.VolunteerIdFromContext(ctx)
	if !ok {
		return nil, fmt.Errorf("unauthorized")
	}

	result, err := r.FeedbackService.CreateNewFeedback(ctx, volId, toModelNewFeedbackInput(feedback))
	if err != nil {
		return nil, err
	}

	return toGenMutationResult(result), nil
}

// AttachFileToFeedback is the resolver for the attachFileToFeedback field.
func (r *mutationResolver) AttachFileToFeedback(ctx context.Context, feedbackID string, file graphql.Upload) (*generated.MutationResult, error) {
	fbInt, err := strconv.Atoi(feedbackID)
	if err != nil {
		return nil, fmt.Errorf("invalid feedback id %s: %w", feedbackID, err)
	}
	data, err := io.ReadAll(file.File)
	if err != nil {
		return nil, fmt.Errorf("failed to read upload: %w", err)
	}

	result, err := r.FeedbackService.AttachFileToFeedback(
		ctx, fbInt, file.Filename, file.ContentType, data,
	)
	if err != nil {
		return nil, err
	}
	return toGenMutationResult(result), nil
}

// LookupValues is the resolver for the lookupValues field.
func (r *queryResolver) LookupValues(ctx context.Context) (*generated.LookupValues, error) {
	lookup, err := r.EventService.FetchLookups(ctx)
	if err != nil {
		return nil, err
	}
	genLookup := toGenLookupValues(*lookup)
	return &genLookup, nil
}

// VolunteerProfile is the resolver for the volunteerProfile field.
func (r *queryResolver) VolunteerProfile(ctx context.Context) (*generated.VolunteerProfile, error) {
	volId, ok := middleware.VolunteerIdFromContext(ctx)
	if !ok {
		return nil, fmt.Errorf("unauthorized")
	}

	profile, err := r.VolunteerService.FetchOwnProfile(ctx, volId)
	if err != nil {
		return nil, err
	}
	return toGenVolunteerProfile(profile), nil
}

// FilteredEventsWithShifts is the resolver for the filteredEventsWithShifts field.
func (r *queryResolver) FilteredEventsWithShifts(ctx context.Context, filter *generated.EventFilterInput) ([]*generated.Event, error) {
	events, err := r.EventService.FetchFilteredEventsWithShifts(ctx, toModelEventFilterInput(filter))
	if err != nil {
		return nil, fmt.Errorf("error calling FetchFilteredEvents: %w", err)
	}
	return toGenEvents(events), nil
}

// EventByID is the resolver for the eventById field.
func (r *queryResolver) EventByID(ctx context.Context, eventID string) (*generated.Event, error) {
	event, err := r.EventService.FetchEventById(ctx, eventID)
	if err != nil {
		return nil, fmt.Errorf("error calling FetchEventById: %w", err)
	}
	return toGenEvent(event), nil
}

// ShiftsForEvent is the resolver for the shiftsForEvent field.
func (r *queryResolver) ShiftsForEvent(ctx context.Context, eventID string) ([]*generated.ShiftView, error) {
	shiftviews, err := r.ShiftService.FetchShiftViewsForEvent(ctx, eventID)
	if err != nil {
		return nil, err
	}
	return toGenShiftViews(shiftviews), nil
}

// OwnShifts is the resolver for the ownShifts field.
func (r *queryResolver) OwnShifts(ctx context.Context, filter generated.ShiftTimeFilter) ([]*generated.VolunteerShift, error) {
	volId, ok := middleware.VolunteerIdFromContext(ctx)
	if !ok {
		return nil, fmt.Errorf("unauthorized")
	}

	shifts, err := r.ShiftService.FetchOwnShifts(ctx, volId, toModelShiftTimeFilter(filter))
	if err != nil {
		return nil, err
	}

	return toGenVolunteerShifts(shifts), nil
}

// OwnFeedback is the resolver for the ownFeedback field.
func (r *queryResolver) OwnFeedback(ctx context.Context) ([]*generated.VolunteerFeedback, error) {
	volId, ok := middleware.VolunteerIdFromContext(ctx)
	if !ok {
		return nil, fmt.Errorf("unauthorized")
	}

	fb, err := r.FeedbackService.FetchOwnFeedback(ctx, volId)
	if err != nil {
		return nil, err
	}
	return toGenVolunteerFeedbacks(fb), nil
}

// Attachment is the resolver for the attachment field.
func (r *queryResolver) Attachment(ctx context.Context, attachmentID string) (*generated.AttachmentDownload, error) {
	aInt, err := strconv.Atoi(attachmentID)
	if err != nil {
		return nil, fmt.Errorf("invalid attachmentId")
	}
	dl, err := r.FeedbackService.FetchAttachment(ctx, aInt)
	if err != nil {
		return nil, err
	}
	return &generated.AttachmentDownload{
		Filename: dl.Filename,
		MimeType: dl.MimeType,
		Data:     dl.Data,
	}, nil
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//  - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//    it when you're done.
//  - You have helper methods in this file. Move them out to keep these resolver files clean.
/*
	func (r *queryResolver) FilteredEvents(ctx context.Context, filter *generated.EventFilterInput) ([]*generated.Event, error) {
	events, err := r.EventService.FetchFilteredEvents(ctx, toModelEventFilterInput(filter))
	if err != nil {
		return nil, fmt.Errorf("error calling FetchFilteredEvents: %w", err)
	}
	return toGenEvents(events), nil
}
*/
