package volunteer

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.84

import (
	"context"
	"fmt"
	"volunteer-scheduler/graph/volunteer/generated"
	"volunteer-scheduler/middleware"
)

// AddVolunteerFeedbackNote is the resolver for the addVolunteerFeedbackNote field.
func (r *mutationResolver) AddVolunteerFeedbackNote(ctx context.Context, note generated.VolunteerFeedbackNoteInput) (*generated.MutationResult, error) {
	volId, ok := middleware.VolunteerIdFromContext(ctx)
	if !ok {
		return nil, fmt.Errorf("unauthorized")
	}

	result, err := r.FeedbackService.AddVolunteerFeedbackNote(ctx, volId, toModelVolunteerFeedbackNoteInput(note))
	if err != nil {
		return nil, err
	}
	return toGenMutationResult(result), nil
}

// UpdateOwnProfile is the resolver for the updateOwnProfile field.
func (r *mutationResolver) UpdateOwnProfile(ctx context.Context, profile generated.UpdateOwnProfileInput) (*generated.VolunteerMutationResult, error) {
	volId, ok := middleware.VolunteerIdFromContext(ctx)
	if !ok {
		return nil, fmt.Errorf("unauthorized")
	}

	modProf := toModelUpdateOwnProfileInput(&profile)
	result, err := r.VolunteerService.UpdateOwnProfile(ctx, volId, *modProf)
	if err != nil {
		return nil, err
	}

	return toGenVolunteerMutationResult(result), nil
}

// AssignSelfToShift is the resolver for the assignSelfToShift field.
func (r *mutationResolver) AssignSelfToShift(ctx context.Context, shiftID string) (*generated.MutationResult, error) {
	volId, ok := middleware.VolunteerIdFromContext(ctx)
	if !ok {
		return nil, fmt.Errorf("unauthorized")
	}

	result, err := r.ShiftService.AssignSelfToShift(ctx, shiftID, volId)
	if err != nil {
		return nil, err
	}

	return toGenMutationResult(result), nil
}

// CancelOwnShift is the resolver for the cancelOwnShift field.
func (r *mutationResolver) CancelOwnShift(ctx context.Context, shiftID string) (*generated.MutationResult, error) {
	volId, ok := middleware.VolunteerIdFromContext(ctx)
	if !ok {
		return nil, fmt.Errorf("unauthorized")
	}

	result, err := r.ShiftService.CancelOwnShift(ctx, shiftID, volId)
	if err != nil {
		return nil, err
	}

	return toGenMutationResult(result), nil
}

// EventShiftViews is the resolver for the eventShiftViews field.
func (r *queryResolver) EventShiftViews(ctx context.Context, eventID string) ([]*generated.EventShiftView, error) {
	sv, err := r.ShiftService.FetchEventShiftViews(ctx, eventID)
	if err != nil {
		return nil, err
	}
	return toGenEventShiftViews(sv), nil
}

// EventViews is the resolver for the eventViews field.
func (r *queryResolver) EventViews(ctx context.Context, filter *generated.VolunteerEventFilterInput) ([]*generated.EventView, error) {
	volId, ok := middleware.VolunteerIdFromContext(ctx)
	if !ok {
		return nil, fmt.Errorf("unauthorized")
	}
	ev, err := r.EventService.FetchEventViews(ctx, toModelVolunteerEventFilterInput(filter), &volId)
	if err != nil {
		return nil, err
	}
	return toGenEventViews(ev), nil
}

// EventView is the resolver for the eventView field.
func (r *queryResolver) EventView(ctx context.Context, eventID string) (*generated.EventView, error) {
	e, err := r.EventService.FetchEventView(ctx, eventID)
	if err != nil {
		return nil, err
	}
	return toGenEventView(e), nil
}

// OwnAttachment is the resolver for the ownAttachment field.
func (r *queryResolver) OwnAttachment(ctx context.Context, attachmentID int) (*generated.FeedbackAttachmentView, error) {
	volId, ok := middleware.VolunteerIdFromContext(ctx)
	if !ok {
		return nil, fmt.Errorf("unauthorized")
	}
	att, err := r.FeedbackService.FetchOwnAttachment(ctx, attachmentID, volId)
	if err != nil {
		return nil, err
	}
	return toGenFeedbackAttachmentView(att), nil
}

// OwnFeedback is the resolver for the ownFeedback field.
func (r *queryResolver) OwnFeedback(ctx context.Context) ([]*generated.FeedbackView, error) {
	volId, ok := middleware.VolunteerIdFromContext(ctx)
	if !ok {
		return nil, fmt.Errorf("unauthorized")
	}

	fb, err := r.FeedbackService.FetchOwnFeedback(ctx, volId)
	if err != nil {
		return nil, err
	}
	return toGenFeedbackViews(fb), nil
}

// OwnProfile is the resolver for the ownProfile field.
func (r *queryResolver) OwnProfile(ctx context.Context) (*generated.VolunteerView, error) {
	volId, ok := middleware.VolunteerIdFromContext(ctx)
	if !ok {
		return nil, fmt.Errorf("unauthorized")
	}
	v, err := r.VolunteerService.FetchOwnProfile(ctx, volId)
	if err != nil {
		return nil, err
	}
	return toGenVolunteerView(v), nil
}

// OwnShifts is the resolver for the ownShifts field.
func (r *queryResolver) OwnShifts(ctx context.Context, filter generated.ShiftTimeFilter) ([]*generated.VolunteerShiftView, error) {
	volId, ok := middleware.VolunteerIdFromContext(ctx)
	if !ok {
		return nil, fmt.Errorf("unauthorized")
	}

	shifts, err := r.VolunteerService.FetchOwnShifts(ctx, volId, toModelShiftTimeFilter(filter))
	if err != nil {
		return nil, err
	}

	return toGenVolunteerShiftViews(shifts), nil
}
