package volunteer

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.84

import (
	"context"
	"volunteer-scheduler/graph/volunteer/generated"
)

// LookupValues is the resolver for the lookupValues field.
func (r *queryResolver) LookupValues(ctx context.Context) (*generated.LookupValues, error) {
	lookup, err := r.EventService.FetchLookups(ctx)
	if err != nil {
		return nil, err
	}
	genLookup := toGenLookupValues(*lookup)
	return &genLookup, nil
}

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
